module.exports = Object.freeze({
  GET_POPULAR_TOPICS_METHOD: "ctrlGetPopularTopics",
  GET_RECOMMENDED_VIDEOS_METHOD: "ctrlGetRecommendedVideos",
  BOOKMARK_ARTICLE_METHOD: "ctrlBookmarkArticle",
  CREATE_LIST_METHOD: "ctrlCreateList",
  DELETE_LIST_METHOD: "ctrlDeleteList",
  ADD_ITEM_TO_LIST_METHOD: "ctrlAddItemToList",
  DELETE_ITEM_FROM_LIST_METHOD: "ctrlDeleteItemFromList",
  GET_LIST_ITEMS_METHOD: "ctrlGetListItems",
  GET_EVENTS_METHOD: "ctrlGetEvents",
  POST_EVENTS_METHOD: "ctrlPostEvents",
  UNBOOKMARK_ARTICLE_METHOD: "ctrlUnBookmarkArticle",
  FOLLOW_UNFOLLOW_SECTION_METHOD: "ctrlFollowUnFollowSection",
  NEWSTIP_METHOD: "ctrlPostNewstip",
  EMAIL_PREFS_CONFIG_METHOD: "ctrlEmailPrefsConfig",
  APP_CONFIG_METHOD: "ctrlAddAppConfigs",
  USERS_EMAIL_PREFS_METHOD: "ctrlUsersEmailPrefs",
  GET_USERS_EMAIL_PREFS_METHOD: "ctrlGetUsersEmailPrefs",
  ATTEND_EVENT_METHOD: "ctrlAttendAnEvent",
  UNATTEND_EVENT_METHOD: "ctrlUnAttendAnEvent",
  EVENTS_COLLECTIONS: ["featured-events", "upcoming-events", "past-events"],
  NOTIF_PREFS_CONFIG_METHOD: "ctrlNotifPrefsConfig",
  USERS_NOTIF_PREFS_METHOD: "ctrlUsersNotifPrefs",
  NEWSLETTERSUBS_METHOD: "ctrlPostNewsLetterSubs",
  SUB_TYPE: { PODCAST: "podcast", EVENTS: "event" },
  SECTION_ID: "sectionId",
  CONTENT_ALIAS: "content_alias",
  FOLLOW_SECTIONS: "follow_sections",
  SUPPORT_EMAIL: "support_email",
  DOMAIN: "domain",
  OFFLINE_MESSAGE: "offline_message",
  TERM_URL: "term_url",
  PRIVACY_POLICY: "privacy_policy",
  NAME: "name",
  LIST_NAME: "list_name",
  EMAIL_PREFS: "email_prefs",
  NOTIF_PREFS: "notif_prefs",
  ITEM_ID: "item_id",
  ITEM: "item",
  IMG: "img",
  EXISTS: "exists",
  ID: "id",
  STATUS: "status",
  TITLE: "title",
  PUBLISHED_DATE: "published_date",
  LIST: "list",
  BOOKMARK_LIST: "bookmarks",
  UNFOLLOW_SECTIONS: "unfollow_sections",
  ARTICLE_ID: "articleId",
  EVENT_ID: "eventId",
  INVALID_INPUT: "Invalid Input",
  OFFSET: "offset",
  SIZE: "size",
  FROM: "from",
  SUCCESS: "success",
  JOB_SUCCESS_MSG: "Job Completed Successfully",
  JOB_FAILED_MSG: "Job Execution Failed, Please try agin",
  ARTICLE_BOOKMARKED_SUCCESSFULLY: "Article Bookmarked Successfully",
  LIST_CREATED_SUCCESSFULLY: "list Created Successfully",
  LIST_DELETED_SUCCESSFULLY: "list Deleted Successfully",
  ITEM_ADDED_SUCCESSFULLY: "item added Successfully",
  ITEM_REMOVED_SUCCESSFULLY: "Item removed Successfully",
  ITEM_ADDED_FAILURE: "Failed to add Item, Please contact Admin",
  ARTICLE_UNBOOKMARKED_SUCCESSFULLY:
    "Article Removed from Bookmarks Successfully",
  FOLLOW_SECTION_UPDATED_SUCCESSFULLY: "Followed Sections Updated Successfully",
  EMAIL_PREFERENCES_CONFIG_UPDATED_SUCCESSFULLY:
    "Email Preferences Configuration Updated Successfully",
  NOTIF_PREFERENCES_CONFIG_UPDATED_SUCCESSFULLY:
    "Notification Preferences Configuration Updated Successfully",
  APP_CONFIG_UPDATED_SUCCESSFULLY: "App configurations updated Successfully",
  USER_EMAIL_PREFERENCES_UPDATED_SUCCESSFULLY:
    "Users email preferences updated successfully",
  USER_NOTIFICATION_PREFERENCES_UPDATED_SUCCESSFULLY:
    "Users Notification preferences updated successfully",
  EMAIL_PREFS_NOT_AVAILABLE: "Email preferences not available",
  NOTIF_PREFS_NOT_AVAILABLE: "Notification preferences not available",
  APP_CONFIG_NOT_AVAILABLE: "App Configurations not available",
  USER_NOT_AVAILABLE: "User not available",
  USER_DELETED_SUCCESSFULLY: "User deleted Successfully",
  EVENT_ADDED_SUCCESSFULLY: "Event Added to the Attending List Successfully",
  EVENT_REMOVED_SUCCESSFULLY: "Event Removed from Attending List Successfully",
  ADMIN_ERROR_MSG: "Something went wrong, Please Contact Admin",
  ACCESS_FORBIDDEN: "Access Forbidden",
  USER_DELETE_ERR_MSG: "Unable to delete User. Please Contact Admin",
  LIST_PRESENT: "list already present",
  LIST_NOT_PRESENT: "list not present",
  FALSE_STR: "false",
  SPACE_STR: " ",
  CONFIG_FILE_PATH: "/tmp/app-config.json",
  ENVIRONMENTS: { DEV: "dev", PROD: "prod" },
  NEWS_LETTER_ERRORS: {
    "Member Exists": {
      title: "Unable to sign up",
      subtitle: "Email address already exists",
    },
    "Invalid Resource": {
      title: "Email is invalid",
      subtitle: "Please enter a valid email address",
    },
  },
  NEWS_LETTER_SUCCESS: {
    title: "Thank you for signing up",
    subtitle: "Check your email inbox to verify and receive our newsletter",
  },
  WEBHOOK_OPTINMASTER_SUCCESS: {
    title: "Data Recieved",
    subtitle: "Data Pushed",
  },
  CARDS_TYPE: {
    EmailSubscriptionDropCard: "EmailSubscriptionDropCard",
  },
  CARDS_ALIGNMENT: {
    VERTICAL: "vertical",
  },
  SECTION: "section",
  THE_DROP_AM_PM: "The Drop AM/PM",
  SUBSCRIBED: "subscribed",
  UNSUBSCRIBED: "unsubscribed",
  METHOD_POST: "post",
  METHOD_PUT: "put",
  MAILCHIMP: "mailChimp",
  MAILCHIMP_API_KEY: "MAILCHIMP_API_KEY",
  MAILCHIMP_ENDPOINT: "mailchimp.endpoint",
  MAILCHIMP_LISTID: "mailchimp.listId",
  CONTENT_TYPE: "Content-Type",
  APPLICATION_JSON: "application/json",
  INTERNAL_SERVER_ERROR: "internal server error",
  LISTS: "lists",
  EMAIL: "email",
  IMAGE: "image",

  CHANNELS_KEY_VAL_MAPPING: {
    OUTBOUND_WIRES: "OutboundWires",
    TWITTER: "Twitter",
  },
  CHANNEL_KEYS: {
    OUTBOUND_WIRES_KEY: "OUTBOUND_WIRES",
    TWITTER_KEY: "TWITTER",
  },
  NEWSTIP: {
    NEWSTIP: "newstip",
    NEWSTIP_SENT_SUCCESSFULLY: "Newstip sent successfully",
    DETAILS: "details",
    // SUBJECT: "Hot News Tip",
    SUBJECT: "Alert - General Tip Submission",
    TITLE: "General Tip Submission",
    SUBMITTED: "SUBMITTED",
    FROM_USERNAME: "Newstips Form",
    FROM_EMAIL: "api-system@mipo.news",
    AT: "at",
    DETAILS_OF_THE_NEWSTIP: "Details of the news tip",
    NAME: "Name",
    EMAIL_ADDRESS: "Email address",
  },
  NOTIFICATION: {
    ARTICLE_ID: "article_id",
  },
  NEWS_LETTER_SUBSCRIPTION_ADDED_SUCCESSFULLY:
    "Newsletter Subscription added Successfully",
  NEWSLETTER: {
    SUBSCRIPTION_TABLE: "SUBSCRIPTION",
    SUBSCRIPTION_ID_SEQ: "subscription_id_seq",
    USER_TYPE: { EXISTING: "EXISTING", NEW: "NEW" },
    AUDIENCE_ID: "audience_id",
    ID: "id",
    LIST_ID_TO_SID: "List_Id_To_Sid",
    AUDIENCE_TO_ID: "AUDIENCE_TO_ID",
    ACTION: { UNSUB: "unsub" },
    TYPE: { UNSUBSCRIBE: "unsubscribe", SUBSCRIBE: "subscribe" },
  },
  DATE_TIME_FORMAT: {
    MMM_DD: "MMM DD",
    HOUR_MONTH_12_SMALL: "hh:mm a",
  },
  OPTIN_MONSTER: {
    DEFAULT_ID: "e545c8a0ad",
  },
  QUERY_LITERALS: {
    SELECT_FIELDS_MAILCHIMP_UNSUB:
      "u.id as uid, s.id as sid, s.audience_id as list_id",
  },
});
